name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    # Applies to all files under models/example/
    staging:
      +materialized: view    # Staging layers should always build as fast, clean views
    marts:
      +materialized: table    # Core business dimension/fact tables build as physical tables
